version: '3'
services:
  api:
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    ports:
      - 8000:8000
  client:
    build:
      context: ./frontend/movies
      dockerfile: Dockerfile
    ports:
      - 3000:3000
